// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Boxerp.Client.GtkSharp.Controls {
    
    
    public partial class DateControl {
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Boxerp.Client.GtkSharp.Controls.DateControl
            Stetic.BinContainer.Attach(this);
            this.Name = "Boxerp.Client.GtkSharp.Controls.DateControl";
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
