// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Boxerp.Client.GtkSharp.Controls {
    
    
    public partial class ComboBox {
        
        private Gtk.ComboBox _combo;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget Boxerp.Client.GtkSharp.Controls.ComboBox
            Stetic.BinContainer.Attach(this);
            this.Name = "Boxerp.Client.GtkSharp.Controls.ComboBox";
            // Container child Boxerp.Client.GtkSharp.Controls.ComboBox.Gtk.Container+ContainerChild
            this.combobox1 = new Gtk.ComboBox();
            this.combobox1.Name = "combobox1";
            this.Add(this.combobox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
