// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Boxerp.Client.GtkSharp.Controls {
    
    
    public partial class IntegerTextBoxControl {
        
        private Gtk.Entry _textBox;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget Boxerp.Client.GtkSharp.Controls.IntegerTextBoxControl
            Stetic.BinContainer.Attach(this);
            this.Name = "Boxerp.Client.GtkSharp.Controls.IntegerTextBoxControl";
            // Container child Boxerp.Client.GtkSharp.Controls.IntegerTextBoxControl.Gtk.Container+ContainerChild
            this._textBox = new Gtk.Entry();
            this._textBox.CanFocus = true;
            this._textBox.Name = "_textBox";
            this._textBox.IsEditable = true;
            this._textBox.InvisibleChar = '●';
            this.Add(this._textBox);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this._textBox.KeyReleaseEvent += new Gtk.KeyReleaseEventHandler(this.OnKeyReleased);
        }
    }
}
