// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Table table1;
    
    private Boxerp.Client.GtkSharp.Controls.IntegerTextBoxControl _desk;
    
    private Boxerp.Client.GtkSharp.Controls.TextBoxControl _email;
    
    private Boxerp.Client.GtkSharp.Controls.TextBoxControl _password;
    
    private Boxerp.Client.GtkSharp.Controls.TextBoxControl _username;
    
    private Gtk.Button button3;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Button button4;
    
    private Gtk.Button button2;
    
    private Gtk.Button button1;
    
    private Gtk.Label label1;
    
    private Gtk.Label label2;
    
    private Gtk.Label label3;
    
    private Gtk.Label label4;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize();
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.table1 = new Gtk.Table(((uint)(5)), ((uint)(2)), false);
        this.table1.Name = "table1";
        this.table1.RowSpacing = ((uint)(6));
        this.table1.ColumnSpacing = ((uint)(6));
        // Container child table1.Gtk.Table+TableChild
        this._desk = new Boxerp.Client.GtkSharp.Controls.IntegerTextBoxControl();
        this._desk.Events = ((Gdk.EventMask)(256));
        this._desk.Name = "_desk";
        this._desk.Integer = 0;
        this._desk.MaxValue = 0;
        this.table1.Add(this._desk);
        Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this._desk]));
        w1.TopAttach = ((uint)(3));
        w1.BottomAttach = ((uint)(4));
        w1.LeftAttach = ((uint)(1));
        w1.RightAttach = ((uint)(2));
        w1.XOptions = ((Gtk.AttachOptions)(4));
        w1.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this._email = new Boxerp.Client.GtkSharp.Controls.TextBoxControl();
        this._email.Events = ((Gdk.EventMask)(256));
        this._email.Name = "_email";
        this.table1.Add(this._email);
        Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this._email]));
        w2.TopAttach = ((uint)(2));
        w2.BottomAttach = ((uint)(3));
        w2.LeftAttach = ((uint)(1));
        w2.RightAttach = ((uint)(2));
        w2.XOptions = ((Gtk.AttachOptions)(4));
        w2.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this._password = new Boxerp.Client.GtkSharp.Controls.TextBoxControl();
        this._password.Events = ((Gdk.EventMask)(256));
        this._password.Name = "_password";
        this.table1.Add(this._password);
        Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this._password]));
        w3.TopAttach = ((uint)(1));
        w3.BottomAttach = ((uint)(2));
        w3.LeftAttach = ((uint)(1));
        w3.RightAttach = ((uint)(2));
        w3.XOptions = ((Gtk.AttachOptions)(4));
        w3.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this._username = new Boxerp.Client.GtkSharp.Controls.TextBoxControl();
        this._username.Events = ((Gdk.EventMask)(256));
        this._username.Name = "_username";
        this.table1.Add(this._username);
        Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this._username]));
        w4.LeftAttach = ((uint)(1));
        w4.RightAttach = ((uint)(2));
        w4.XOptions = ((Gtk.AttachOptions)(4));
        w4.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.button3 = new Gtk.Button();
        this.button3.CanFocus = true;
        this.button3.Name = "button3";
        this.button3.UseUnderline = true;
        this.button3.Label = Mono.Unix.Catalog.GetString("Change Business Object");
        this.table1.Add(this.button3);
        Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.button3]));
        w5.TopAttach = ((uint)(4));
        w5.BottomAttach = ((uint)(5));
        w5.XOptions = ((Gtk.AttachOptions)(4));
        w5.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.button4 = new Gtk.Button();
        this.button4.CanFocus = true;
        this.button4.Name = "button4";
        this.button4.UseUnderline = true;
        this.button4.Label = Mono.Unix.Catalog.GetString("Show Business Object");
        this.hbox1.Add(this.button4);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox1[this.button4]));
        w6.Position = 0;
        w6.Expand = false;
        w6.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.button2 = new Gtk.Button();
        this.button2.CanFocus = true;
        this.button2.Name = "button2";
        this.button2.UseUnderline = true;
        this.button2.Label = Mono.Unix.Catalog.GetString("Redo");
        this.hbox1.Add(this.button2);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox1[this.button2]));
        w7.Position = 1;
        w7.Expand = false;
        w7.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = Mono.Unix.Catalog.GetString("Undo");
        this.hbox1.Add(this.button1);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox1[this.button1]));
        w8.Position = 2;
        w8.Expand = false;
        w8.Fill = false;
        this.table1.Add(this.hbox1);
        Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.hbox1]));
        w9.TopAttach = ((uint)(4));
        w9.BottomAttach = ((uint)(5));
        w9.LeftAttach = ((uint)(1));
        w9.RightAttach = ((uint)(2));
        w9.XOptions = ((Gtk.AttachOptions)(4));
        w9.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Username:");
        this.table1.Add(this.label1);
        Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
        w10.XOptions = ((Gtk.AttachOptions)(4));
        w10.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Password:");
        this.table1.Add(this.label2);
        Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
        w11.TopAttach = ((uint)(1));
        w11.BottomAttach = ((uint)(2));
        w11.XOptions = ((Gtk.AttachOptions)(4));
        w11.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("Email:");
        this.table1.Add(this.label3);
        Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
        w12.TopAttach = ((uint)(2));
        w12.BottomAttach = ((uint)(3));
        w12.XOptions = ((Gtk.AttachOptions)(4));
        w12.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("Desk:");
        this.table1.Add(this.label4);
        Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
        w13.TopAttach = ((uint)(3));
        w13.BottomAttach = ((uint)(4));
        w13.XOptions = ((Gtk.AttachOptions)(4));
        w13.YOptions = ((Gtk.AttachOptions)(4));
        this.Add(this.table1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 410;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.button4.Clicked += new System.EventHandler(this.OnShowClicked);
        this.button2.Clicked += new System.EventHandler(this.OnRedoClicked);
        this.button1.Clicked += new System.EventHandler(this.OnUndoClicked);
        this.button3.Clicked += new System.EventHandler(this.OnChangeClicked);
    }
}
