// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Label label1;
    
    private Gtk.Entry _name;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Label label2;
    
    private Gtk.Entry _description;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Label label3;
    
    private Gtk.VBox vbox2;
    
    private Gtk.HBox hbox4;
    
    private Gtk.Button button1;
    
    private Gtk.Button button2;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize();
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Bindable Business Objects");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Homogeneous = true;
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Name:");
        this.hbox1.Add(this.label1);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this._name = new Gtk.Entry();
        this._name.CanFocus = true;
        this._name.Name = "_name";
        this._name.IsEditable = true;
        this._name.InvisibleChar = '●';
        this.hbox1.Add(this._name);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this._name]));
        w2.Position = 1;
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Homogeneous = true;
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Description:");
        this.hbox2.Add(this.label2);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.label2]));
        w4.Position = 0;
        w4.Expand = false;
        w4.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this._description = new Gtk.Entry();
        this._description.CanFocus = true;
        this._description.Name = "_description";
        this._description.IsEditable = true;
        this._description.InvisibleChar = '●';
        this.hbox2.Add(this._description);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this._description]));
        w5.Position = 1;
        this.vbox1.Add(this.hbox2);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Homogeneous = true;
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("Age:");
        this.hbox3.Add(this.label3);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox3[this.label3]));
        w7.Position = 0;
        w7.Expand = false;
        w7.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        this.hbox3.Add(this.vbox2);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox3[this.vbox2]));
        w8.Position = 1;
        this.vbox1.Add(this.hbox3);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
        w9.Position = 2;
        w9.Expand = false;
        w9.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox4 = new Gtk.HBox();
        this.hbox4.Name = "hbox4";
        this.hbox4.Homogeneous = true;
        // Container child hbox4.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = Mono.Unix.Catalog.GetString("Undo");
        this.hbox4.Add(this.button1);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox4[this.button1]));
        w10.Position = 0;
        // Container child hbox4.Gtk.Box+BoxChild
        this.button2 = new Gtk.Button();
        this.button2.CanFocus = true;
        this.button2.Name = "button2";
        this.button2.UseUnderline = true;
        this.button2.Label = Mono.Unix.Catalog.GetString("Redo");
        this.hbox4.Add(this.button2);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox4[this.button2]));
        w11.Position = 1;
        this.vbox1.Add(this.hbox4);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
        w12.Position = 3;
        w12.Expand = false;
        w12.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 400;
        this.DefaultHeight = 167;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this._name.Changed += new System.EventHandler(this.OnNameChanged);
        this._description.Changed += new System.EventHandler(this.OnDescriptionChanged);
        this.button1.Clicked += new System.EventHandler(this.OnUndoClicked);
        this.button2.Clicked += new System.EventHandler(this.OnRedoClicked);
    }
}
