// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace mvcSample1 {
    
    
    public partial class UserEditView {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Table table1;
        
        private Boxerp.Client.GtkSharp.Controls.CheckBox _active;
        
        private Boxerp.Client.GtkSharp.Controls.IntegerTextBox _desk;
        
        private Boxerp.Client.GtkSharp.Controls.TextBox _email;
        
        private Boxerp.Client.GtkSharp.Controls.TextBox _group;
        
        private Boxerp.Client.GtkSharp.Controls.TextBox _username;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label label5;
        
        private Gtk.HButtonBox hbuttonbox1;
        
        private Gtk.Button button5;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget mvcSample1.UserEditView
            Stetic.BinContainer.Attach(this);
            this.Name = "mvcSample1.UserEditView";
            // Container child mvcSample1.UserEditView.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(5)), ((uint)(2)), true);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            this.table1.BorderWidth = ((uint)(4));
            // Container child table1.Gtk.Table+TableChild
            this._active = new Boxerp.Client.GtkSharp.Controls.CheckBox();
            this._active.CanFocus = true;
            this._active.Name = "_active";
            this.table1.Add(this._active);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this._active]));
            w1.TopAttach = ((uint)(4));
            w1.BottomAttach = ((uint)(5));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this._desk = new Boxerp.Client.GtkSharp.Controls.IntegerTextBox();
            this._desk.Events = ((Gdk.EventMask)(256));
            this._desk.Name = "_desk";
            this._desk.Integer = 0;
            this._desk.MaxValue = 0;
            this.table1.Add(this._desk);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this._desk]));
            w2.TopAttach = ((uint)(3));
            w2.BottomAttach = ((uint)(4));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this._email = new Boxerp.Client.GtkSharp.Controls.TextBox();
            this._email.Events = ((Gdk.EventMask)(256));
            this._email.Name = "_email";
            this.table1.Add(this._email);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this._email]));
            w3.TopAttach = ((uint)(2));
            w3.BottomAttach = ((uint)(3));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this._group = new Boxerp.Client.GtkSharp.Controls.TextBox();
            this._group.Events = ((Gdk.EventMask)(256));
            this._group.Name = "_group";
            this.table1.Add(this._group);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this._group]));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this._username = new Boxerp.Client.GtkSharp.Controls.TextBox();
            this._username.Events = ((Gdk.EventMask)(256));
            this._username.Name = "_username";
            this.table1.Add(this._username);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this._username]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Group:");
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Username:");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w7.TopAttach = ((uint)(1));
            w7.BottomAttach = ((uint)(2));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Email:");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w8.TopAttach = ((uint)(2));
            w8.BottomAttach = ((uint)(3));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Desk Number:");
            this.table1.Add(this.label4);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
            w9.TopAttach = ((uint)(3));
            w9.BottomAttach = ((uint)(4));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Active");
            this.table1.Add(this.label5);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
            w10.TopAttach = ((uint)(4));
            w10.BottomAttach = ((uint)(5));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox1.Add(this.table1);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox1[this.table1]));
            w11.Position = 0;
            w11.Expand = false;
            w11.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbuttonbox1 = new Gtk.HButtonBox();
            this.hbuttonbox1.Name = "hbuttonbox1";
            this.hbuttonbox1.Spacing = 6;
            this.hbuttonbox1.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.button5 = new Gtk.Button();
            this.button5.CanFocus = true;
            this.button5.Name = "button5";
            this.button5.UseUnderline = true;
            this.button5.Label = Mono.Unix.Catalog.GetString("Close");
            this.hbuttonbox1.Add(this.button5);
            Gtk.ButtonBox.ButtonBoxChild w12 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.button5]));
            w12.Expand = false;
            w12.Fill = false;
            w12.Padding = ((uint)(6));
            this.vbox1.Add(this.hbuttonbox1);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox1]));
            w13.Position = 1;
            w13.Expand = false;
            w13.Fill = false;
            w13.Padding = ((uint)(6));
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.button5.Clicked += new System.EventHandler(this.OnClose);
        }
    }
}
