// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Boxerp.Client.GtkSharp {
    
    
    public partial class QuestionDialog {
        
        private Gtk.HBox hbox1;
        
        private Gtk.Image image;
        
        private Gtk.Label label;
        
        private Gtk.Button button22;
        
        private Gtk.Button button24;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget Boxerp.Client.GtkSharp.QuestionDialog
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Boxerp.Client.GtkSharp.QuestionDialog";
            this.Title = Mono.Unix.Catalog.GetString("Question");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            this.HasSeparator = false;
            // Internal child Boxerp.Client.GtkSharp.QuestionDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Events = ((Gdk.EventMask)(256));
            w1.Name = "dialog_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog_VBox.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            // Container child hbox1.Gtk.Box+BoxChild
            this.image = new Gtk.Image();
            this.image.Name = "image";
            this.image.Pixbuf = Stetic.IconLoader.LoadIcon("gtk-dialog-info", 16);
            this.hbox1.Add(this.image);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.image]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            w2.Padding = ((uint)(5));
            // Container child hbox1.Gtk.Box+BoxChild
            this.label = new Gtk.Label();
            this.label.Name = "label";
            this.label.LabelProp = "Info";
            this.hbox1.Add(this.label);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.label]));
            w3.Position = 1;
            w1.Add(this.hbox1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(w1[this.hbox1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            w4.Padding = ((uint)(5));
            // Internal child Boxerp.Client.GtkSharp.QuestionDialog.ActionArea
            Gtk.HButtonBox w5 = this.ActionArea;
            w5.Events = ((Gdk.EventMask)(256));
            w5.Name = "Boxerp.Client.GtkSharp.Lib.QuestionDialog_ActionArea";
            w5.Spacing = 6;
            w5.BorderWidth = ((uint)(5));
            w5.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child Boxerp.Client.GtkSharp.Lib.QuestionDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button22 = new Gtk.Button();
            this.button22.CanDefault = true;
            this.button22.CanFocus = true;
            this.button22.Name = "button22";
            // Container child button22.Gtk.Container+ContainerChild
            Gtk.Alignment w6 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            w6.Name = "GtkAlignment";
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w7 = new Gtk.HBox();
            w7.Name = "GtkHBox";
            w7.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w8 = new Gtk.Image();
            w8.Name = "image34";
            w8.Pixbuf = Stetic.IconLoader.LoadIcon("gtk-no", 16);
            w7.Add(w8);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w10 = new Gtk.Label();
            w10.Name = "GtkLabel";
            w10.LabelProp = Mono.Unix.Catalog.GetString("No");
            w7.Add(w10);
            w6.Add(w7);
            this.button22.Add(w6);
            this.AddActionWidget(this.button22, -9);
            Gtk.ButtonBox.ButtonBoxChild w14 = ((Gtk.ButtonBox.ButtonBoxChild)(w5[this.button22]));
            w14.Expand = false;
            w14.Fill = false;
            // Container child Boxerp.Client.GtkSharp.Lib.QuestionDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button24 = new Gtk.Button();
            this.button24.CanDefault = true;
            this.button24.CanFocus = true;
            this.button24.Name = "button24";
            // Container child button24.Gtk.Container+ContainerChild
            Gtk.Alignment w15 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            w15.Name = "GtkAlignment1";
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            Gtk.HBox w16 = new Gtk.HBox();
            w16.Name = "GtkHBox1";
            w16.Spacing = 2;
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Image w17 = new Gtk.Image();
            w17.Name = "image35";
            w17.Pixbuf = Stetic.IconLoader.LoadIcon("gtk-yes", 16);
            w16.Add(w17);
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Label w19 = new Gtk.Label();
            w19.Name = "GtkLabel1";
            w19.LabelProp = Mono.Unix.Catalog.GetString("Yes");
            w16.Add(w19);
            w15.Add(w16);
            this.button24.Add(w15);
            this.AddActionWidget(this.button24, -8);
            Gtk.ButtonBox.ButtonBoxChild w23 = ((Gtk.ButtonBox.ButtonBoxChild)(w5[this.button24]));
            w23.Position = 1;
            w23.Expand = false;
            w23.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 99;
            this.Show();
            this.button22.Clicked += new System.EventHandler(this.OnNo);
            this.button24.Clicked += new System.EventHandler(this.OnYes);
        }
    }
}
