// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Boxerp.Client.GtkSharp {
    
    
    public partial class InfoExtendedDialog {
        
        private Gtk.Button button6;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget Boxerp.Client.GtkSharp.InfoExtendedDialog
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Boxerp.Client.GtkSharp.InfoExtendedDialog";
            this.Title = Mono.Unix.Catalog.GetString("InfoExtendedDialog");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child Boxerp.Client.GtkSharp.InfoExtendedDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Events = ((Gdk.EventMask)(256));
            w1.Name = "dialog_VBox";
            w1.BorderWidth = ((uint)(2));
            // Internal child Boxerp.Client.GtkSharp.InfoExtendedDialog.ActionArea
            Gtk.HButtonBox w2 = this.ActionArea;
            w2.Events = ((Gdk.EventMask)(256));
            w2.Name = "Boxerp.Client.GtkSharp.Lib.InfoExtendedDialog_ActionArea";
            w2.Spacing = 6;
            w2.BorderWidth = ((uint)(5));
            w2.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child Boxerp.Client.GtkSharp.Lib.InfoExtendedDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button6 = new Gtk.Button();
            this.button6.CanDefault = true;
            this.button6.CanFocus = true;
            this.button6.Name = "button6";
            this.button6.Label = "button6";
            this.AddActionWidget(this.button6, 0);
            Gtk.ButtonBox.ButtonBoxChild w3 = ((Gtk.ButtonBox.ButtonBoxChild)(w2[this.button6]));
            w3.Expand = false;
            w3.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
