// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Stetic.SteticGenerated {
    
    
    internal class button7 {
        
        public static void Build(Gtk.Button cobj) {
            System.Collections.Hashtable bindings = new System.Collections.Hashtable();
            // Widget button7
            cobj.CanDefault = true;
            cobj.CanFocus = true;
            cobj.Name = "button7";
            if ((cobj.Child != null)) {
                cobj.Child.ShowAll();
            }
            cobj.Label = "button7";
            cobj.Show();
            System.Reflection.FieldInfo[] fields = cobj.GetType().GetFields(((System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic) | System.Reflection.BindingFlags.Instance));
            for (int n = 0; (n < fields.Length); n = (n + 1)) {
                System.Reflection.FieldInfo field = fields[n];
                object widget = bindings[field.Name];
                if (((widget != null) && field.FieldType.IsInstanceOfType(widget))) {
                    field.SetValue(cobj, widget);
                }
            }
        }
    }
}
