// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace testApp3 {
    
    
    public partial class MenuWindow {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label label1;
        
        private Gtk.Button button1;
        
        private Gtk.Button button2;
        
        private Gtk.Button button3;
        
        private Gtk.Button button4;
        
        private Gtk.Button button5;
        
        private Gtk.Button button6;
        
        private Gtk.Button button7;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget testApp3.MenuWindow
            this.Name = "testApp3.MenuWindow";
            this.Title = Mono.Unix.Catalog.GetString("MenuWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child testApp3.MenuWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Gtk Databinding tests\nSome cases don't include databinding but basic widget tests");
            this.label1.Justify = ((Gtk.Justification)(2));
            this.vbox1.Add(this.label1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.label1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.button1 = new Gtk.Button();
            this.button1.CanFocus = true;
            this.button1.Name = "button1";
            this.button1.UseUnderline = true;
            this.button1.Label = Mono.Unix.Catalog.GetString("Basic databinding tests");
            this.vbox1.Add(this.button1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.button1]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.button2 = new Gtk.Button();
            this.button2.CanFocus = true;
            this.button2.Name = "button2";
            this.button2.UseUnderline = true;
            this.button2.Label = Mono.Unix.Catalog.GetString("ListView (using Items property + AutoCreateColumns) tests");
            this.vbox1.Add(this.button2);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.button2]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.button3 = new Gtk.Button();
            this.button3.CanFocus = true;
            this.button3.Name = "button3";
            this.button3.UseUnderline = true;
            this.button3.Label = Mono.Unix.Catalog.GetString("ListView (using BoundItems property + AutoCreateColumns) tests");
            this.vbox1.Add(this.button3);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.button3]));
            w4.Position = 3;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.button4 = new Gtk.Button();
            this.button4.CanFocus = true;
            this.button4.Name = "button4";
            this.button4.UseUnderline = true;
            this.button4.Label = Mono.Unix.Catalog.GetString("DataGrid (using Items property + BindingDescriptor) tests");
            this.vbox1.Add(this.button4);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox1[this.button4]));
            w5.Position = 4;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.button5 = new Gtk.Button();
            this.button5.CanFocus = true;
            this.button5.Name = "button5";
            this.button5.UseUnderline = true;
            this.button5.Label = Mono.Unix.Catalog.GetString("DataGrid (using BoundItems property + AutoCreateColumns) tests");
            this.vbox1.Add(this.button5);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.button5]));
            w6.Position = 5;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.button6 = new Gtk.Button();
            this.button6.CanFocus = true;
            this.button6.Name = "button6";
            this.button6.UseUnderline = true;
            this.button6.Label = Mono.Unix.Catalog.GetString("DataGrid (using BindDataTable) tests");
            this.vbox1.Add(this.button6);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.button6]));
            w7.Position = 6;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.button7 = new Gtk.Button();
            this.button7.CanFocus = true;
            this.button7.Name = "button7";
            this.button7.UseUnderline = true;
            this.button7.Label = Mono.Unix.Catalog.GetString("ComboBox tests");
            this.vbox1.Add(this.button7);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox1[this.button7]));
            w8.Position = 7;
            w8.Expand = false;
            w8.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 629;
            this.DefaultHeight = 330;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnExit);
            this.button1.Clicked += new System.EventHandler(this.OnBasicDataBinding);
            this.button2.Clicked += new System.EventHandler(this.OnBasicListView);
            this.button3.Clicked += new System.EventHandler(this.OnListViewDataBinding);
            this.button4.Clicked += new System.EventHandler(this.OnDataGridTests);
            this.button6.Clicked += new System.EventHandler(this.OnDataGridDataTable);
            this.button7.Clicked += new System.EventHandler(this.OnComboBoxTests);
        }
    }
}
