// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace testApp3 {
    
    
    public partial class ComboBoxTests {
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget testApp3.ComboBoxTests
            this.Name = "testApp3.ComboBoxTests";
            this.Title = Mono.Unix.Catalog.GetString("ComboBoxTests");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
