-- ================================================================================
--   postgres SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   postgres
--   Generated at:      Wed Jan 25 10:32:49 2006
--   Input Files:       bd1.dia
-- 
-- ================================================================================



-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Jan 25 10:32:48 2006
--     Input Files:       bd1.dia



-- Generated Permissions Drops
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Jan 25 10:32:48 2006
--     Input Files:       bd1.dia




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Jan 25 10:32:48 2006
--     Input Files:       bd1.dia



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Jan 25 10:32:48 2006
--     Input Files:       bd1.dia

drop table Users cascade ;
drop table Groups cascade ;
drop table Enterprises cascade ;
drop table Ctrld_actions cascade ;
drop table Ctrld_sections cascade ;
drop table Permissions cascade ;
drop table Tables cascade ;
drop table Error_codes cascade ;
drop table Sessions cascade ;


-- Generated SQL Schema
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Jan 25 10:32:48 2006
--     Input Files:       bd1.dia


-- Users
create table Users (
  id                        integer not null,
  id_group                  integer,
  user_name                 varchar(20),
  password                  varchar(50),
  published                 boolean,
  constraint pk_Users primary key (id)
) ;

-- Groups
create table Groups (
  id                        integer not null,
  id_enterprise             integer,
  group_name                varchar(20),
  published                 boolean,
  constraint pk_Groups primary key (id)
) ;

-- Enterprises
create table Enterprises (
  id                        integer not null,
  name                      varchar(50),
  published                 boolean,
  description               varchar(200),
  constraint pk_Enterprises primary key (id)
) ;

-- Ctrld_actions
create table Ctrld_actions (
  id                        integer not null,
  name                      varchar(30),
  description               varchar(50),
  constraint pk_Ctrld_actions primary key (id)
) ;

-- Ctrld_sections
create table Ctrld_sections (
  id                        integer not null,
  name                      varchar(40),
  description               varchar(60),
  constraint pk_Ctrld_sections primary key (id)
) ;

-- Permissions
create table Permissions (
  id_group                  integer not null,
  id_ctrld_actions          integer not null,
  id_ctrld_sections         integer not null,
  constraint pk_Permissions primary key (id_group,id_ctrld_actions,id_ctrld_sections)
) ;

-- Tables
create table Tables (
  id                        integer not null,
  name                      varchar(30),
  description               varchar(50),
  constraint pk_Tables primary key (id)
) ;

-- Error_codes
create table Error_codes (
  id                        integer,
  description               varchar(50)
) ;

-- Sessions
create table Sessions (
  id                        integer,
  key                       varchar(50),
  id_user                   integer,
  active                    boolean,
  started                   varchar(30),
  finished                  varchar(30)
) ;











-- Generated SQL Views
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Jan 25 10:32:48 2006
--     Input Files:       bd1.dia




-- Generated Permissions
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Jan 25 10:32:48 2006
--     Input Files:       bd1.dia



-- Generated SQL Insert statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Jan 25 10:32:48 2006
--     Input Files:       bd1.dia



-- Generated SQL Constraints
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Wed Jan 25 10:32:48 2006
--     Input Files:       bd1.dia


